package com.currencyconverter.model

class CurrencyTypes {
    val currencies: Array<String> = arrayOf(
        "ARS-BRL : Peso Argentino / Real Brasileiro",
        "ARS-BTC : Peso Argentino / Bitcoin",
        "ARS-CHF : Peso Argentino / Franco Suíço",
        "ARS-ETH : Peso Argentino / Ethereum",
        "ARS-JPY : Peso Argentino / Iene Japonês",
        "ARS-LTC : Peso Argentino / Litecoin",
        "AUD-BRL : Dólar Australiano / Real Brasileiro",
        "AUD-BTC : Dólar Australiano / Bitcoin",
        "AUD-CHF : Dólar Australiano / Franco Suíço",
        "AUD-ETH : Dólar Australiano / Ethereum",
        "AUD-JPY : Dólar Australiano / Iene Japonês",
        "AUD-LTC : Dólar Australiano / Litecoin",
        "BRL-ARS : Real Brasileiro / Peso Argentino",
        "BRL-AUD : Real Brasileiro / Dólar Australiano",
        "BRL-BTC : Real Brasileiro / Bitcoin",
        "BRL-CAD : Real Brasileiro / Dólar Canadense",
        "BRL-CHF : Real Brasileiro / Franco Suíço",
        "BRL-CNY : Real Brasileiro / Yuan Chinês",
        "BRL-ETH : Real Brasileiro / Ethereum",
        "BRL-EUR : Real Brasileiro / Euro",
        "BRL-GBP : Real Brasileiro / Libra Esterlina",
        "BRL-ILS : Real Brasileiro / Novo Shekel Israelense",
        "BRL-JPY : Real Brasileiro / Iene Japonês",
        "BRL-LTC : Real Brasileiro / Litecoin",
        "BRL-USD : Real Brasileiro / Dólar Americano",
        "BTC-ARS : Bitcoin / Peso Argentino",
        "BTC-AUD : Bitcoin / Dólar Australiano",
        "BTC-BRL : Bitcoin / Real Brasileiro",
        "BTC-CAD : Bitcoin / Dólar Canadense",
        "BTC-CHF : Bitcoin / Franco Suíço",
        "BTC-CNY : Bitcoin / Yuan Chinês",
        "BTC-ETH : Bitcoin / Ethereum",
        "BTC-EUR : Bitcoin / Euro",
        "BTC-GBP : Bitcoin / Libra Esterlina",
        "BTC-ILS : Bitcoin / Novo Shekel Israelense",
        "BTC-JPY : Bitcoin / Iene Japonês",
        "BTC-LTC : Bitcoin / Litecoin",
        "BTC-USD : Bitcoin / Dólar Americano",
        "CAD-BRL : Dólar Canadense / Real Brasileiro",
        "CAD-BTC : Dólar Canadense / Bitcoin",
        "CAD-CHF : Dólar Canadense / Franco Suíço",
        "CAD-ETH : Dólar Canadense / Ethereum",
        "CAD-EUR : Dólar Canadense / Euro",
        "CAD-JPY : Dólar Canadense / Iene Japonês",
        "CAD-LTC : Dólar Canadense / Litecoin",
        "CAD-USD : Dólar Canadense / Dólar Americano",
        "CHF-ARS : Franco Suíço / Peso Argentino",
        "CHF-AUD : Franco Suíço / Dólar Australiano",
        "CHF-BRL : Franco Suíço / Real Brasileiro",
        "CHF-BTC : Franco Suíço / Bitcoin",
        "CHF-CAD : Franco Suíço / Dólar Canadense",
        "CHF-ETH : Franco Suíço / Ethereum",
        "CHF-EUR : Franco Suíço / Euro",
        "CHF-JPY : Franco Suíço / Iene Japonês",
        "CHF-LTC : Franco Suíço / Litecoin",
        "CHF-USD : Franco Suíço / Dólar Americano",
        "CNY-BRL : Yuan Chinês / Real Brasileiro",
        "CNY-BTC : Yuan Chinês / Bitcoin",
        "CNY-CHF : Yuan Chinês / Franco Suíço",
        "CNY-ETH : Yuan Chinês / Ethereum",
        "CNY-EUR : Yuan Chinês / Euro",
        "CNY-JPY : Yuan Chinês / Iene Japonês",
        "CNY-LTC : Yuan Chinês / Litecoin",
        "CNY-USD : Yuan Chinês / Dólar Americano",
        "ETH-ARS : Ethereum / Peso Argentino",
        "ETH-AUD : Ethereum / Dólar Australiano",
        "ETH-BRL : Ethereum / Real Brasileiro",
        "ETH-BTC : Ethereum / Bitcoin",
        "ETH-CAD : Ethereum / Dólar Canadense",
        "ETH-CHF : Ethereum / Franco Suíço",
        "ETH-CNY : Ethereum / Yuan Chinês",
        "ETH-EUR : Ethereum / Euro",
        "ETH-GBP : Ethereum / Libra Esterlina",
        "ETH-ILS : Ethereum / Novo Shekel Israelense",
        "ETH-JPY : Ethereum / Iene Japonês",
        "ETH-LTC : Ethereum / Litecoin",
        "ETH-USD : Ethereum / Dólar Americano",
        "EUR-ARS : Euro / Peso Argentino",
        "EUR-AUD : Euro / Dólar Australiano",
        "EUR-BRL : Euro / Real Brasileiro",
        "EUR-BTC : Euro / Bitcoin",
        "EUR-CAD : Euro / Dólar Canadense",
        "EUR-CHF : Euro / Franco Suíço",
        "EUR-CNY : Euro / Yuan Chinês",
        "EUR-ETH : Euro / Ethereum",
        "EUR-GBP : Euro / Libra Esterlina",
        "EUR-ILS : Euro / Novo Shekel Israelense",
        "EUR-JPY : Euro / Iene Japonês",
        "EUR-LTC : Euro / Litecoin",
        "EUR-USD : Euro / Dólar Americano",
        "GBP-ARS : Libra Esterlina / Peso Argentino",
        "GBP-AUD : Libra Esterlina / Dólar Australiano",
        "GBP-BRL : Libra Esterlina / Real Brasileiro",
        "GBP-BTC : Libra Esterlina / Bitcoin",
        "GBP-CAD : Libra Esterlina / Dólar Canadense",
        "GBP-CHF : Libra Esterlina / Franco Suíço",
        "GBP-CNY : Libra Esterlina / Yuan Chinês",
        "GBP-ETH : Libra Esterlina / Ethereum",
        "GBP-EUR : Libra Esterlina / Euro",
        "GBP-ILS : Libra Esterlina / Novo Shekel Israelense",
        "GBP-JPY : Libra Esterlina / Iene Japonês",
        "GBP-LTC : Libra Esterlina / Litecoin",
        "GBP-USD : Libra Esterlina / Dólar Americano",
        "ILS-BRL : Novo Shekel Israelense / Real Brasileiro",
        "ILS-BTC : Novo Shekel Israelense / Bitcoin",
        "ILS-CHF : Novo Shekel Israelense / Franco Suíço",
        "ILS-CAD : Novo Shekel Israelense / Dólar Canadense",
        "ILS-ETH : Novo Shekel Israelense / Ethereum",
        "ILS-EUR : Novo Shekel Israelense / Euro",
        "ILS-GBP : Novo Shekel Israelense / Libra Esterlina",
        "ILS-JPY : Novo Shekel Israelense / Iene Japonês",
        "ILS-LTC : Novo Shekel Israelense / Litecoin",
        "ILS-USD : Novo Shekel Israelense / Dólar Americano",
        "JPY-ARS : Iene Japonês / Peso Argentino",
        "JPY-AUD : Iene Japonês / Dólar Australiano",
        "JPY-BRL : Iene Japonês / Real Brasileiro",
        "JPY-BTC : Iene Japonês / Bitcoin",
        "JPY-CAD : Iene Japonês / Dólar Canadense",
        "JPY-CHF : Iene Japonês / Franco Suíço",
        "JPY-CNY : Iene Japonês / Yuan Chinês",
        "JPY-ETH : Iene Japonês / Ethereum",
        "JPY-EUR : Iene Japonês / Euro",
        "JPY-GBP : Iene Japonês / Libra Esterlina",
        "JPY-ILS : Iene Japonês / Novo Shekel Israelense",
        "JPY-LTC : Iene Japonês / Litecoin",
        "JPY-USD : Iene Japonês / Dólar Americano",
        "LTC-ARS : Litecoin / Peso Argentino",
        "LTC-AUD : Litecoin / Dólar Australiano",
        "LTC-BRL : Litecoin / Real Brasileiro",
        "LTC-BTC : Litecoin / Bitcoin",
        "LTC-CAD : Litecoin / Dólar Canadense",
        "LTC-CHF : Litecoin / Franco Suíço",
        "LTC-CNY : Litecoin / Yuan Chinês",
        "LTC-ETH : Litecoin / Ethereum",
        "LTC-EUR : Litecoin / Euro",
        "LTC-GBP : Litecoin / Libra Esterlina",
        "LTC-ILS : Litecoin / Novo Shekel Israelense",
        "LTC-JPY : Litecoin / Iene Japonês",
        "LTC-USD : Litecoin / Dólar Americano",
        "USD-ARS : Dólar Americano / Peso Argentino",
        "USD-AUD : Dólar Americano / Dólar Australiano",
        "USD-BRL : Dólar Americano / Real Brasileiro",
        "USD-BTC : Dólar Americano / Bitcoin",
        "USD-CAD : Dólar Americano / Dólar Canadense",
        "USD-CHF : Dólar Americano / Franco Suíço",
        "USD-CNY : Dólar Americano / Yuan Chinês",
        "USD-ETH : Dólar Americano / Ethereum",
        "USD-EUR : Dólar Americano / Euro",
        "USD-GBP : Dólar Americano / Libra Esterlina",
        "USD-ILS : Dólar Americano / Novo Shekel Israelense",
        "USD-JPY : Dólar Americano / Iene Japonês",
        "USD-LTC : Dólar Americano / Litecoin",
        "USD-RUB : Dólar Americano / Rublo Russo",
        "USD-XRP : Dólar Americano / XRP",
        "XRP-AUD : XRP / Dólar Australiano",
        "XRP-BRL : XRP / Real Brasileiro",
        "XRP-BTC : XRP / Bitcoin",
        "XRP-CAD : XRP / Dólar Canadense",
        "XRP-CHF : XRP / Franco Suíço",
        "XRP-CNY : XRP / Yuan Chinês",
        "XRP-ETH : XRP / Ethereum",
        "XRP-EUR : XRP / Euro",
        "XRP-GBP : XRP / Libra Esterlina",
        "XRP-ILS : XRP / Novo Shekel Israelense",
        "XRP-JPY : XRP / Iene Japonês",
        "XRP-LTC : XRP / Litecoin",
        "XRP-USD : XRP / Dólar Americano"
    )
}